[package]
name = "oxide_core"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Oxide core"

[lib]
name = "oxide_core"
path = "lib.rs"

[dependencies]
