[package]
name = "oxide_render"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rendering library for Oxide"

[lib]
name = "oxide_render"
path = "lib.rs"

[dependencies]
