[package]
name = "oxide_editor"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
serde = { version = "1", features = ["derive"], optional = true }
faux = "0.1"