[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clippy]
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
command = "cargo"

[tasks.clean]
args = ["clean"]
command = "cargo"

[tasks.cleanbuild]
args = ["build"]
command = "cargo"
dependencies = ["clean"]
