name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Rust nightly build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test with profiling
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - name: Run grcov
        run: |
          mkdir coverage
          ./grcov ./target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" \
                  --excl-line '#\[|=> panic!|unreachable!|Io\(std::io::Error\)' \
                  --excl-br-line '#\[|=> panic!|unreachable!|assert_..!|assert_approx_eq!' -o ./coverage/lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ${{ steps.coverage.outputs.report }}
          token: ${{ secrets.CODECOV_TOKEN }}
